# Generated by Django 2.1.3 on 2018-11-14 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('image', models.ImageField(upload_to='meal_images/')),
                ('category', models.CharField(choices=[('d', 'Desayunos'), ('com', 'Comidas'), ('e', 'Entradas'), ('p', 'Postres'), ('c', 'Complementos'), ('b', 'Bebidas')], max_length=100)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardapp.Restaurant')),
            ],
        ),
    ]
