# Generated by Django 2.1.3 on 2018-11-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0003_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='cook_time',
            field=models.IntegerField(default=0),
        ),
    ]
