# Generated by Django 2.1.3 on 2018-11-15 00:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0004_meal_cook_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('comission', models.FloatField()),
                ('total', models.FloatField()),
                ('status', models.IntegerField(choices=[(1, 'Preparando'), (2, 'Listo'), (3, 'Entregado')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardapp.Customer')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardapp.Restaurant')),
            ],
        ),
    ]
