# Generated by Django 2.1.3 on 2018-12-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0007_auto_20181115_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='extras',
            field=models.CharField(default='', max_length=50),
        ),
    ]
